blank_issues_enabled: false
contact_links:
  - name: Original vanilla version
    url: https://github.com/billalben/notekeeper
    about: Issues with the pre-React version belong in the original repository.
